import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";
import Provider from "@/Redux/Provider/ReduxProvider";
import ReactQuery from "@/components/Providers/ReactQuery";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const westcoast = localFont({
  src: "../../public/fonts/westcoast/Westcoast.ttf",
  variable: "--font-westcoast",
});

const westcoastline = localFont({
  src: "../../public/fonts/westcoast/WestcoastLine.ttf",
  variable: "--font-westcoastline",
});

const krakens = localFont({
  src: "../../public/fonts/TheKrakens/krakens.ttf",
  variable: "--font-krakens",
});

export const metadata = {
  title: "Candy Kush",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <ReactQuery>
      <html lang={params.lang}>
        <body
          className={`${poppins.className} ${westcoast.variable}  ${westcoastline.variable}  ${krakens.variable} flex justify-center items-center`}
        >
          <div className="min-h-screen w-full max-w-[698.7px]  flex justify-center items-center overflow-x-hidden">
            <Provider>
              {children}
              {/* Wrap children with Template */}
            </Provider>
          </div>
        </body>
      </html>
    </ReactQuery>
  );
}
